package:
    name: root
    version: 5.34.36
    #version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} # bug, doesn't work for now: https://github.com/conda/conda-build/issues/357
source:
    #fn: root_v5.34.36.source.tar.gz
    #url: https://root.cern.ch/download/root_v5.34.36.source.tar.gz
    git_url: https://github.com/root-mirror/root
    git_tag: v5-34-36
    patches:

build:
    number: 46
    string: py{{ environ.get('PY_VER','') }}_clang503 # [osx]
    string: py{{ environ.get('PY_VER','') }}_gcc4.8.2 # [linux]
    detect_binary_files_with_prefix: True

requirements:
    build:
        - python   
        - openssl
        - qt # [linux]
        - sqlite 
        - fftw
        - pcre
        - libxml2
        - graphviz # [linux]
        #- cmake >=3.2.3
        - gsl >=1.16
        - xz # [osx]
        - freetype # [osx]
        - krb5 # [osx]
        #- libx11 2.7.7 #[osx]
        - libpng #[osx]
        - jpeg #[osx]
        - libtiff #[osx]
        
    run:
        - python
        - openssl
        - qt # [linux]
        - sqlite
        - graphviz # [linux]
        - libxml2
        - fftw
        - pcre
        - gsl >=1.16
        - gcc >=4.8.2 # [linux]
        - xz # [osx]
        - freetype # [osx]
        - krb5 # [osx]
        #- libx11 2.7.7 # [osx]
        - libpng #[osx]
        - jpeg #[osx]
        - libtiff #[osx]
        
test:

   files:
         - ../tests/test_root.py
         - ../tests/test_stl.py

   commands:
         - root -b -q
         - which root
         - source ${PREFIX}/bin/thisroot.sh
         - python test_root.py
         - python test_stl.py
         
   imports:
        - ROOT
        
   requires:
         - numpy
         - rootpy

about:
    home: http://root.cern.ch/
    license: LGPL v2.1

