package:
  name: root_pandas
  version: 1

source:
  git_url: https://github.com/ibab/root_pandas.git
  git_tag: master
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 2
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python # [{{ environ.get('PY_VER') }}]
    - numpy
    - pandas
    - root_numpy

  run:
    - python # [{{ environ.get('PY_VER') }}]
    - numpy
    - pandas
    - root_numpy

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ibab/root_pandas
  summary: ' A Python module for conveniently loading/saving ROOT files as pandas DataFrames'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
