package:
  name: linux-headers
  version: 2.6.32

build:
  number: 1
  detect_binary_files_with_prefix: True

source:
  fn: linux-2.6.32.27.tar.xz
  url: https://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.32.27.tar.xz
  sha1: bbf9a89ad7ec034027765b88f8eddff038e05eef


about:
  home: http://www.gnu.org/software/libc/
  license: LGPL
  summary: "Any Unix-like operating system needs a C library: the library which defines the ``system calls'' and other basic facilities such as open, malloc, printf, exit..."
