package:
  name: root
  version: 5.34.32

source:
  fn: root_v5.34.32.source.tar.gz
  url: http://root.cern.ch/download/root_v5.34.32.source.tar.gz

requirements:
  build:
    - python
    - gsl
    - fftw
    - pcre
    - qt
    - openssl
    
    
  run:
    - python
    - gsl
    - qt
    - openssl

build:
  number: 0

  detect_binary_files_with_prefix: true

test:
  # Python imports
  imports:
   # - ROOT

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    #- root-config --version

about:
  home: http://root.cern.ch
  license: LGPLv2
  summary: "Analysis package for particle physics"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
