package:
  name: pcre
  version: !!str 8.35

source:
  fn: pcre-8.35.tar.bz2
  url: http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.35.tar.bz2
  md5: 6aacb23986adccd9b3bc626c00979958
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 7
  detect_binary_files_with_prefix: True
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.


requirements:
  build:

  run:

test:
  # Python imports
  imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pcre-config --version

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pcre.org/
  license: Perl Compatible Regular Expressions
  summary: "C library implementing PERL-style regular expressions"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
