package:
  name: gsl
  version: 1.16

source:
  fn: gsl-1.16.tar.gz
  url: http://ftp.club.cc.cmu.edu/pub/gnu/gsl/gsl-1.16.tar.gz

build:
  number: 2 # [osx]
  number: 2 # [linux]
  detect_binary_files_with_prefix: True
requirements:
  build:
    - gcc

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL 3
