package:
  name: gcc
  version: 4.8.2

source:
  fn: 9f699b42394bd2754d9f77427553d923
  #url: http://www.netgull.com/gcc/releases/gcc-4.8.2/gcc-4.8.2.tar.bz2
  url: http://pkgs.fedoraproject.org/repo/pkgs/cross-gcc/gcc-4.8.2-20140120.tar.bz2/md5/
  #md5: a3d7d63b9cb6b6ea049469a0c4a43c9d
  md5: 9f699b42394bd2754d9f77427553d923
build:
  detect_binary_files_with_prefix: True
  number: 25

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog 0.18.0
    #- binutils 2.25
    # Do not make gcc a build dependency (you will need to add it to the PATH manually)
  run:
    - gmp >=4.2
    - mpfr >=2.4.0
    - mpc >=0.8.0
    - isl
    - cloog 0.18.0
    - glibc # [linux]
    - linux-headers # [linux]  
    
about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
