package:
    name: xrootd
    version: 4.1.2
    #version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} # bug, doesn't work for now: https://github.com/conda/conda-build/issues/357
source:
    fn: xrootd-4.1.2.tar.gz
    url: http://xrootd.org/download/v4.1.2/xrootd-4.1.2.tar.gz
    #git_url: https://github.com/root-mirror/root
    #git_tag: heads/v6-04-00-patches@v6-04-02-110-g264f10d
    #patches:
    #    - python34.patch
    #    - python34_1.patch
    #path: /home/daniela/anaconda_backup/anaconda/root-6.04.02
build:
    number: 1
    string: py{{ environ.get('PY_VER','') }}_clang503 # [osx]
    string: py{{ environ.get('PY_VER','') }}_gcc4.8.2 # [linux]
    detect_binary_files_with_prefix: True

requirements:
    build:
        - python  # [{{ environ.get('PY_VER') }}]     
        - openssl
        - gcc 4.8.2 # [linux]
        
    run:
        - python  # [{{ environ.get('PY_VER') }}]
        - openssl
        - gcc 4.8.2 # [linux]
