package:
    name: root6
    version: 6.04.02
source:
    #fn: root_v6.04.02.source.tar.gz
    #url: https://root.cern.ch/download/root_v6.04.02.source.tar.gz
    git_url: https://github.com/root-mirror/root
    git_tag: v6-04-02
build:
    number: 2
    string: py27_gcc5
    
    detect_binary_files_with_prefix: True
    
    has_prefix_files:
        - bin/thisroot.csh
        - bin/thisroot.sh
    binary_has_prefix_files:
        - bin/root
      #  - bin/genmap
      #  - bin/root-config
      #  - bin/hadd
      #  - bin/pq2
      #  - bin/genreflex
      #  - bin/proofserv
      #  - bin/proofserv.exe
      #  - bin/rmkdepend
      #  - bin/root.exe
      #  - bin/genreflex
      #  - bin/hist2workspace
      #  - bin/prepareHistFactory
        - bin/rootcint
      #  - bin/roots
      #  - bin/genreflex-rootcint
      #  - bin/memprobe
        - bin/proofd
      #  - bin/rlibmap
        - bin/rootd
      #  - bin/roots.exe
      #  - bin/ssh2rpd
      #  - bin/xpdtest
      #  - "*so"
      #  - "*dll"
      #  - "*dylib"
    
requirements:
    build:
        - python # [py27]
        - openssl
        - qt
        - sqlite
        - fftw
        - pcre
        
    run:
        - python # [py27]
        - openssl
        - qt
        - sqlite

test:
    imports:

    commands:

about:
    home: http://root.cern.ch/
    license: LGPL v2.1

