package:
  name: python-snappy
  version: !!str 0.5

source:
  fn: python-snappy-0.5.tar.gz
  url: https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.5.tar.gz
  md5: 044fb0ac21888c0b4eee0c4f15e75504
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 20
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python # [{{ environ.get('PY_VER') }}]
    - snappy

  run:
    - python # [{{ environ.get('PY_VER') }}]
    - snappy

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/andrix/python-snappy
  license: BSD License
  summary: 'Python library for the snappy compression library from Google'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
