package:
    name: root
    version: 5.34.14

source:
    git_url: https://github.com/root-mirror/root
    git_tag: v5-34-21

build:
    number: 0

    has_prefix_files:
        - bin/thisroot.csh
        - bin/thisroot.sh
    binary_has_prefix_files:
        - bin/root
        - bin/genmap
        - bin/root-config
        - bin/hadd
        - bin/pq2
        - bin/genreflex
        - bin/proofserv
        - bin/proofserv.exe
        - bin/rmkdepend
        - bin/root.exe
        - bin/genreflex
        - bin/hist2workspace
        - bin/prepareHistFactory
        - bin/rootcint
        - bin/roots
        - bin/genreflex-rootcint
        - bin/memprobe
        - bin/proofd
        - bin/rlibmap
        - bin/rootd
        - bin/roots.exe
        - bin/ssh2rpd
        - bin/xpdtest
        - "*so"
        - "*dll"
        - "*dylib"
requirements:
    build:
        - python
        - openssl
        - qt
        - sqlite
        - fftw
        - graphviz
        - pcre

    run:
        - python
        - openssl
        - qt
        - sqlite
        - fftw
        - graphviz
        - pcre

test:
    imports:

    commands:

about:
    home: http://root.cern.ch/
    license: LGPL v2.1
