package:
  name: cloog
  version: 0.18.1

source:
  fn: cloog-0.18.1.tar.gz
  url: http://www.bastoul.net/cloog/pages/download/count.php3?url=./cloog-0.18.1.tar.gz

build:
  number: 2
  detect_binary_files_with_prefix: True

requirements:
  build:
    - gmp >=5.0.2
    - isl

  run:
    - gmp
    - isl
